version: "3"
services:
  db:
    image: db_image
    build: ./db
    volumes:
      - pg_logs:/var/log/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_PORT={DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    container_name: "${DB_HOST}"

  vm_patrol:
    image: vm_patrol_image
    build:
      context: ./vm_patrol
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - VM_IP=${VM_IP}
      - VM_USERNAME=${VM_USERNAME}
      - VM_PASSWORD=${VM_PASSWORD}
      - VM_PORT=${VM_PORT}
    volumes:
      - pg_logs:/var/log/
    container_name: "${VM_PATROL}"

volumes:
  pg_data:
  pg_logs:
networks:
  default:
    name: my_network
    external: true
